name: ggc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - bifrost
  - biopython
  - bcbio-gff
  - diamond
  - hmmer
  - mafft
  - panaroo >=1.28
  - pytorch
  - snp-sites
  - zlib
  - pthread-stubs
  - matplotlib
  - graph-tool >=2.35
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
  - intbitset
  - networkx
  - pybind11
  - eigen
  - openblas
  - cmake >= 3.4
  - libgomp
  - llvm-openmp
  - tqdm
  - setuptools
  - make