name: ggc_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - bifrost
  - biopython
  - bcbio-gff
  - diamond
  - hmmer
  - mafft
  - panaroo">=1.2"
  - pytorch
  - snp-sites
  - zlib
  - pthread-stubs
  - matplotlib
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
  - intbitset
  - networkx
  - pybind11
  - uncertainties
  - eigen=3.3
  - openblas
  - cmake">=3.10"
  - libgomp
  - llvm-openmp
  - tqdm
  - setuptools
  - make
  - seaborn
  - rapidnj
  - boost-cpp
  - tbb