name: ggc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch-cpu
  - mkl-devel
  - tbb-devel
  - boost-cpp
  - pip
  - numpy
  - scipy
  - pandas
  - bifrost
  - biopython
  - bcbio-gff
  - diamond
  - hmmer
  - mafft
  - snp-sites
  - zlib
  - pthread-stubs
  - matplotlib
  - xorg-libxi
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxpm
  - xorg-libxaw
  - xorg-libxfixes
  - intbitset
  - networkx
  - pybind11
  - uncertainties
  - eigen=3.3
  - cmake>=3.10
  - libgomp
  - protobuf
  - llvm-openmp
  - tqdm
  - setuptools
  - make
  - seaborn
  - rapidnj
  - python-edlib
  - joblib
  - gffutils
  - cd-hit
  - python-wget