# Python package
# Create and test a Python package on multiple Python versions.

name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: checkout source
      uses: actions/checkout@v3
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: models/ggCallerdb
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Install and run_test.py
      run: |
        PATH=$CONDA/bin/bin:$PATH
        source $CONDA/bin/activate base
        $CONDA/bin/python -m pip install --no-deps --ignore-installed --use-feature=in-tree-build .
        cd test && export GGCALLER_PYTHON=$CONDA/bin/python && $CONDA/bin/python run_test.py
